services:
  - type: web
    name: id-qr-printing
    runtime: python
    pythonVersion: "3.10.8"
    buildCommand: |
      pip install --upgrade pip --no-cache-dir
      pip install -r requirements.txt --no-cache-dir
      mkdir -p data/{participant_list,id_templates,qr_codes}
      [ -f data/active_config.json ] || echo '{}' > data/active_config.json
      mkdir -p static/id_templates
      [ -f static/id_templates/default_template.png ] || touch static/id_templates/default_template.png
      touch data/.ready
    startCommand: "gunicorn --workers 1 --timeout 30 --worker-class sync --bind :$PORT app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: QR_KEY
        generateValue: true
      - key: BASE_DIR
        value: /opt/render/project/src
      - key: FLASK_ENV
        value: production
      - key: MKL_NUM_THREADS
        value: "1"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: OPENBLAS_NUM_THREADS
        value: "1"
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: data_volume
      mountPath: /opt/render/project/src/data
      sizeGB: 1
