services:
  - type: web
    name: id-qr-printing
    runtime: python
    pythonVersion: "3.10.8"
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y libcups2-dev
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p data/{participant_list,id_templates,qr_codes}
      [ -f data/active_config.json ] || echo '{}' > data/active_config.json
      mkdir -p static/id_templates
      [ -f static/id_templates/default_template.png ] || touch static/id_templates/default_template.png
      touch data/.ready
    startCommand: "gunicorn --workers 1 --threads 4 --timeout 300 --worker-class gthread --bind :$PORT app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: QR_KEY
        generateValue: true
      - key: BASE_DIR
        value: /opt/render/project/src
      - key: FLASK_ENV
        value: production
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: data_volume
      mountPath: /opt/render/project/src/data
      sizeGB: 1
