services:
  - type: web
    name: id-qr-printing
    runtime: python
    pythonVersion: "3.10.8"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p data/{participant_list,id_templates,qr_codes}
      # Create default files if they don't exist
      [ -f data/active_config.json ] || echo '{"active_dataset":"sample_employees_dataset.csv","active_template":"template1.png"}' > data/active_config.json
      [ -f static/id_templates/template1.png ] || cp static/id_templates/default_template.png static/id_templates/template1.png
      touch data/.ready
    startCommand: "gunicorn --workers 2 --threads 4 --timeout 120 app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: QR_KEY
        generateValue: true
      - key: BASE_DIR
        value: /opt/render/project/src
      - key: FLASK_ENV
        value: production
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: data_volume
      mountPath: /opt/render/project/src/data
      sizeGB: 1
